dist: trusty
language: node_js
sudo: false

env: NODE_ENV="test"
node_js: 8
addons:
  firefox: latest
notifications:
  email: false

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: npm test
after_success: npm run coverage
